// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(LibrairyContext))]
    partial class LibrairyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("App.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsWritter")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("App.Models.Users.UserStorieGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("StorieId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StorieId");

                    b.HasIndex("UserId");

                    b.ToTable("UserStorieGroups");
                });

            modelBuilder.Entity("App.Models.Users.UserStorieItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("UserStorieGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.HasIndex("UserStorieGroupId");

                    b.ToTable("UserStorieItems");
                });

            modelBuilder.Entity("Book.Models.Choice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NextPage")
                        .HasColumnType("int");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NextPage");

                    b.HasIndex("PageId");

                    b.ToTable("Choice");
                });

            modelBuilder.Entity("Book.Models.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsEnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("StorieId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StorieId");

                    b.ToTable("Page");
                });

            modelBuilder.Entity("Book.Models.Storie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("FirstPage")
                        .HasColumnType("int");

                    b.Property<bool>("Statut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int?>("Tags")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FirstPage");

                    b.ToTable("Storie");
                });

            modelBuilder.Entity("App.Models.Users.UserStorieGroup", b =>
                {
                    b.HasOne("Book.Models.Storie", "Storie")
                        .WithMany()
                        .HasForeignKey("StorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Models.Users.User", "User")
                        .WithMany("StoryGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Storie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Models.Users.UserStorieItem", b =>
                {
                    b.HasOne("Book.Models.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Models.Users.UserStorieGroup", "UserStorieGroup")
                        .WithMany("Items")
                        .HasForeignKey("UserStorieGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("UserStorieGroup");
                });

            modelBuilder.Entity("Book.Models.Choice", b =>
                {
                    b.HasOne("Book.Models.Page", null)
                        .WithMany()
                        .HasForeignKey("NextPage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Book.Models.Page", null)
                        .WithMany("Choices")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Book.Models.Page", b =>
                {
                    b.HasOne("Book.Models.Storie", null)
                        .WithMany()
                        .HasForeignKey("StorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Book.Models.Storie", b =>
                {
                    b.HasOne("Book.Models.Page", null)
                        .WithMany()
                        .HasForeignKey("FirstPage")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("App.Models.Users.User", b =>
                {
                    b.Navigation("StoryGroups");
                });

            modelBuilder.Entity("App.Models.Users.UserStorieGroup", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Book.Models.Page", b =>
                {
                    b.Navigation("Choices");
                });
#pragma warning restore 612, 618
        }
    }
}
